# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = OwlPlay
DESTDIR = ../bin
QT += core opengl gui multimedia widgets openglextensions
CONFIG += debug console
INCLUDEPATH = ./../../include
LIBS += -L"./../../lib"
OBJECTS_DIR += debug
include(OwlPlay.pri)
